export const strings = {
  appName: 'Na Fali',
  navigationDisclaimer: 'Informacje w aplikacji mają charakter pomocniczy. Nie zastępują map ani certyfikowanych systemów nawigacyjnych.',
  offline: 'Brak połączenia. Wyświetlane dane mogą być nieaktualne.',
  retry: 'Spróbuj ponownie',
  loading: 'Ładowanie…',
  noData: 'Brak danych',
  save: 'Zapisz',
  cancel: 'Anuluj',
  login: 'Zaloguj się',
  register: 'Utwórz konto',
  email: 'Adres e-mail',
  password: 'Hasło',
  displayName: 'Nazwa użytkownika',
  permissionLocationTitle: 'Lokalizacja podczas rejsu',
  permissionLocationBody: 'Najpierw poprosimy o dostęp podczas używania aplikacji, a następnie — tylko dla aktywnego rejsu — o dostęp w tle.',
  sharingActive: 'Udostępnianie pozycji jest aktywne',
  sharingStopped: 'Udostępnianie pozycji jest wyłączone',
};
