export const strings = {
  appName: 'Boja',
  navigationDisclaimer: 'Informacje w aplikacji mają charakter pomocniczy. Nie zastępują map ani certyfikowanych systemów nawigacyjnych.',
  offline: 'Brak połączenia. Wyświetlane dane mogą być nieaktualne.',
  retry: 'Spróbuj ponownie',
  loading: 'Ładowanie…',
  noData: 'Brak danych',
  save: 'Zapisz',
  cancel: 'Anuluj',
  login: 'Zaloguj się',
  register: 'Utwórz konto',
  email: 'Adres e-mail',
  password: 'Hasło',
  displayName: 'Nazwa użytkownika',
  permissionLocationTitle: 'Anonimowa pozycja łodzi',
  permissionLocationBody: 'Aplikacja poprosi o dostęp podczas używania oraz w tle, aby okresowo aktualizować anonimową pozycję łodzi.',
  sharingActive: 'Udostępnianie pozycji jest aktywne',
  sharingStopped: 'Brak systemowego dostępu do lokalizacji',
};
